version: '3'

services:
  node-app:
    image: node:14
    working_dir: /app
    volumes:
      - /Users/nacho/Documents/Maestria/Projecto/survey/survey-website/:/app
    command: node ./server.js
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      DATABASE_URI: mongodb://mongo:27017/mydb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongodb_data:

